Repository guardicore/monkey, pull requests merged in 2019-11, with the labels that each got.

#477 Prevent circular import with PBA
  monkey/infection_monkey/exploit/sambacry.py
  monkey/infection_monkey/exploit/sshexec.py
  monkey/infection_monkey/exploit/tools/helpers.py
  monkey/infection_monkey/exploit/tools/http_tools.py
  monkey/infection_monkey/exploit/tools/smb_tools.py
  monkey/infection_monkey/exploit/weblogic.py
  monkey/infection_monkey/monkey.py
  monkey/infection_monkey/network/tools.py
  monkey/infection_monkey/post_breach/actions/users_custom_pba.py
  monkey/infection_monkey/transport/http.py
  monkey/infection_monkey/tunnel.py
Labels: Bug

#481 468/copyright year
  monkey/monkey_island/cc/ui/package-lock.json
  monkey/monkey_island/cc/ui/package.json
  monkey/monkey_island/cc/ui/src/components/pages/LicensePage.js
  monkey/monkey_island/cc/ui/src/styles/App.css
Labels: Bug, UI

#493 https://github.com/pymssql/pymssql/issues/668
  monkey/infection_monkey/requirements_linux.txt
  monkey/infection_monkey/requirements_windows.txt
Labels: Bug

#500 Merge Infection Monkey requirements files
  .travis.yml
  deployment_scripts/deploy_linux.sh
  deployment_scripts/deploy_windows.ps1
  monkey/infection_monkey/readme.md
  monkey/infection_monkey/requirements.txt
  monkey/infection_monkey/requirements_windows.txt
Labels: Documentation, Monkey
