Repository guardicore/monkey, pull requests merged in 2020-05, with the labels that each got.

#643 Hotfix/fix ui build problems
  .travis.yml
  monkey/monkey_island/cc/ui/karma.conf.js
  monkey/monkey_island/cc/ui/package-lock.json
  monkey/monkey_island/cc/ui/package.json
  monkey/monkey_island/cc/ui/src/components/report-components/attack/TechniqueDropdowns.js
Labels: Bug, UI

#632 Monkey telemetry fabrication and tests
  .gitignore
  envs/monkey_zoo/.gitignore
  envs/monkey_zoo/blackbox/README.md
  envs/monkey_zoo/blackbox/analyzers/performance_analyzer.py
  envs/monkey_zoo/blackbox/island_client/monkey_island_client.py
  envs/monkey_zoo/blackbox/island_client/monkey_island_requests.py
  envs/monkey_zoo/blackbox/island_client/supported_request_method.py
  envs/monkey_zoo/blackbox/log_handlers/monkey_log.py
  envs/monkey_zoo/blackbox/log_handlers/test_logs_handler.py
  envs/monkey_zoo/blackbox/test_blackbox.py
  envs/monkey_zoo/blackbox/tests/exploitation.py
  envs/monkey_zoo/blackbox/tests/performance/endpoint_performance_test.py
  envs/monkey_zoo/blackbox/tests/performance/map_generation.py
  envs/monkey_zoo/blackbox/tests/performance/performance_test_config.py
  envs/monkey_zoo/blackbox/tests/performance/performance_test_workflow.py
  envs/monkey_zoo/blackbox/tests/performance/report_generation.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/__init__.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_file_parser.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_multiplier/__init__.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_multiplier/fake_ip_generator.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_multiplier/fake_monkey.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_multiplier/sample_multiplier.py
  envs/monkey_zoo/blackbox/tests/performance/telem_sample_parsing/sample_multiplier/test_fake_ip_generator.py
  envs/monkey_zoo/blackbox/tests/performance/telemetry_performance_test.py
  envs/monkey_zoo/blackbox/utils/gcp_machine_handlers.py
  envs/monkey_zoo/blackbox/utils/json_encoder.py
  monkey/monkey_island/cc/models/test_telem.py
  monkey/monkey_island/cc/resources/log.py
  monkey/monkey_island/cc/resources/monkey.py
  monkey/monkey_island/cc/resources/root.py
  monkey/monkey_island/cc/resources/telemetry.py
  monkey/monkey_island/cc/resources/test/utils/telem_store.py
  monkey/monkey_island/cc/services/config.py
  monkey/monkey_island/cc/services/config_schema.py
  monkey/monkey_island/cc/services/infection_lifecycle.py
  monkey/monkey_island/requirements.txt
Labels: Feature, Island, QA

#646 Added a short summary sentence over each table in the security report
  monkey/monkey_island/cc/ui/src/components/report-components/SecurityReport.js
  monkey/monkey_island/cc/ui/src/components/report-components/security/BreachedServers.js
  monkey/monkey_island/cc/ui/src/components/report-components/security/PostBreach.js
  monkey/monkey_island/cc/ui/src/components/report-components/security/ScannedServers.js
Labels: UI

#647 Smallfixes on persistance/create user attack technique
  monkey/monkey_island/cc/services/attack/attack_schema.py
  monkey/monkey_island/cc/services/attack/technique_reports/T1136.py
  monkey/monkey_island/cc/ui/src/components/attack/techniques/T1136.js
Labels: UI

#645 ZeroTrust performance fixes
  .gitignore
  envs/monkey_zoo/blackbox/test_blackbox.py
  envs/monkey_zoo/blackbox/tests/performance/map_generation_from_telemetries.py
  envs/monkey_zoo/blackbox/tests/performance/performance_test_workflow.py
  envs/monkey_zoo/blackbox/tests/performance/report_generation_from_telemetries.py
  envs/monkey_zoo/blackbox/tests/performance/telemetry_performance_test_workflow.py
  monkey/monkey_island/cc/app.py
  monkey/monkey_island/cc/models/zero_trust/aggregate_finding.py
  monkey/monkey_island/cc/models/zero_trust/event.py
  monkey/monkey_island/cc/models/zero_trust/finding.py
  monkey/monkey_island/cc/models/zero_trust/test_aggregate_finding.py
  monkey/monkey_island/cc/resources/zero_trust/finding_event.py
  monkey/monkey_island/cc/services/reporting/test_zero_trust_service.py
  monkey/monkey_island/cc/services/reporting/zero_trust_service.py
  monkey/monkey_island/cc/testing/README.md
  monkey/monkey_island/cc/testing/profiler_decorator.py
  monkey/monkey_island/cc/ui/src/components/report-components/zerotrust/EventsButton.js
  monkey/monkey_island/cc/ui/src/components/report-components/zerotrust/EventsModal.js
  monkey/monkey_island/cc/ui/src/components/report-components/zerotrust/EventsTimeline.js
  monkey/monkey_island/cc/ui/src/components/report-components/zerotrust/FindingsTable.js
  monkey/monkey_island/cc/ui/src/components/report-components/zerotrust/SkippedEventsTimeline.js
  monkey/monkey_island/cc/ui/src/styles/report/ReportPage.scss
  monkey/monkey_island/linux/install_mongo.sh
Labels: Enhancement

#652 Fix travis script
  .travis.yml
Labels: Bug

#666 Fix reset env state bug
  monkey/monkey_island/cc/ui/src/components/ui-components/StartOverModal.js
Labels: Bug, UI
